// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/yiqinguo/armyant/pkg/models/slave.proto

package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Job struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Connections          int64             `protobuf:"varint,2,opt,name=connections" json:"connections,omitempty"`
	Method               string            `protobuf:"bytes,3,opt,name=method" json:"method,omitempty"`
	Body                 string            `protobuf:"bytes,4,opt,name=body" json:"body,omitempty"`
	Headers              map[string]string `protobuf:"bytes,5,rep,name=headers" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Requests             int64             `protobuf:"varint,6,opt,name=requests" json:"requests,omitempty"`
	Url                  string            `protobuf:"bytes,7,opt,name=url" json:"url,omitempty"`
	Duration             string            `protobuf:"bytes,8,opt,name=duration" json:"duration,omitempty"`
	HistoryId            string            `protobuf:"bytes,9,opt,name=historyId" json:"historyId,omitempty"`
	Name                 string            `protobuf:"bytes,10,opt,name=name" json:"name,omitempty"`
	Master               string            `protobuf:"bytes,11,opt,name=master" json:"master,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_slave_48a80dd1f8c230e6, []int{0}
}
func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (dst *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(dst, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Job) GetConnections() int64 {
	if m != nil {
		return m.Connections
	}
	return 0
}

func (m *Job) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Job) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Job) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *Job) GetRequests() int64 {
	if m != nil {
		return m.Requests
	}
	return 0
}

func (m *Job) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Job) GetDuration() string {
	if m != nil {
		return m.Duration
	}
	return ""
}

func (m *Job) GetHistoryId() string {
	if m != nil {
		return m.HistoryId
	}
	return ""
}

func (m *Job) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Job) GetMaster() string {
	if m != nil {
		return m.Master
	}
	return ""
}

type Stats struct {
	Spec                 *Spec    `protobuf:"bytes,1,opt,name=spec" json:"spec,omitempty"`
	Result               *Result  `protobuf:"bytes,2,opt,name=result" json:"result,omitempty"`
	JobId                string   `protobuf:"bytes,3,opt,name=jobId" json:"jobId,omitempty"`
	HistoryId            string   `protobuf:"bytes,4,opt,name=historyId" json:"historyId,omitempty"`
	InstancdId           string   `protobuf:"bytes,5,opt,name=instancdId" json:"instancdId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stats) Reset()         { *m = Stats{} }
func (m *Stats) String() string { return proto.CompactTextString(m) }
func (*Stats) ProtoMessage()    {}
func (*Stats) Descriptor() ([]byte, []int) {
	return fileDescriptor_slave_48a80dd1f8c230e6, []int{1}
}
func (m *Stats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stats.Unmarshal(m, b)
}
func (m *Stats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stats.Marshal(b, m, deterministic)
}
func (dst *Stats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stats.Merge(dst, src)
}
func (m *Stats) XXX_Size() int {
	return xxx_messageInfo_Stats.Size(m)
}
func (m *Stats) XXX_DiscardUnknown() {
	xxx_messageInfo_Stats.DiscardUnknown(m)
}

var xxx_messageInfo_Stats proto.InternalMessageInfo

func (m *Stats) GetSpec() *Spec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *Stats) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *Stats) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *Stats) GetHistoryId() string {
	if m != nil {
		return m.HistoryId
	}
	return ""
}

func (m *Stats) GetInstancdId() string {
	if m != nil {
		return m.InstancdId
	}
	return ""
}

type Spec struct {
	NumberOfConnections  int64    `protobuf:"varint,1,opt,name=numberOfConnections" json:"numberOfConnections,omitempty"`
	TestType             string   `protobuf:"bytes,2,opt,name=testType" json:"testType,omitempty"`
	NumberOfRequests     int64    `protobuf:"varint,3,opt,name=numberOfRequests" json:"numberOfRequests,omitempty"`
	Method               string   `protobuf:"bytes,4,opt,name=method" json:"method,omitempty"`
	Url                  string   `protobuf:"bytes,5,opt,name=url" json:"url,omitempty"`
	Body                 string   `protobuf:"bytes,6,opt,name=body" json:"body,omitempty"`
	Stream               bool     `protobuf:"varint,7,opt,name=stream" json:"stream,omitempty"`
	TimeoutSeconds       int64    `protobuf:"varint,8,opt,name=timeoutSeconds" json:"timeoutSeconds,omitempty"`
	Client               string   `protobuf:"bytes,9,opt,name=client" json:"client,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Spec) Reset()         { *m = Spec{} }
func (m *Spec) String() string { return proto.CompactTextString(m) }
func (*Spec) ProtoMessage()    {}
func (*Spec) Descriptor() ([]byte, []int) {
	return fileDescriptor_slave_48a80dd1f8c230e6, []int{2}
}
func (m *Spec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Spec.Unmarshal(m, b)
}
func (m *Spec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Spec.Marshal(b, m, deterministic)
}
func (dst *Spec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Spec.Merge(dst, src)
}
func (m *Spec) XXX_Size() int {
	return xxx_messageInfo_Spec.Size(m)
}
func (m *Spec) XXX_DiscardUnknown() {
	xxx_messageInfo_Spec.DiscardUnknown(m)
}

var xxx_messageInfo_Spec proto.InternalMessageInfo

func (m *Spec) GetNumberOfConnections() int64 {
	if m != nil {
		return m.NumberOfConnections
	}
	return 0
}

func (m *Spec) GetTestType() string {
	if m != nil {
		return m.TestType
	}
	return ""
}

func (m *Spec) GetNumberOfRequests() int64 {
	if m != nil {
		return m.NumberOfRequests
	}
	return 0
}

func (m *Spec) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Spec) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Spec) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Spec) GetStream() bool {
	if m != nil {
		return m.Stream
	}
	return false
}

func (m *Spec) GetTimeoutSeconds() int64 {
	if m != nil {
		return m.TimeoutSeconds
	}
	return 0
}

func (m *Spec) GetClient() string {
	if m != nil {
		return m.Client
	}
	return ""
}

type Result struct {
	BytesRead            int64    `protobuf:"varint,1,opt,name=bytesRead" json:"bytesRead,omitempty"`
	BytesWritten         int64    `protobuf:"varint,2,opt,name=bytesWritten" json:"bytesWritten,omitempty"`
	TimeTakenSeconds     float32  `protobuf:"fixed32,3,opt,name=timeTakenSeconds" json:"timeTakenSeconds,omitempty"`
	Req1Xx               int64    `protobuf:"varint,4,opt,name=req1xx" json:"req1xx,omitempty"`
	Req2Xx               int64    `protobuf:"varint,5,opt,name=req2xx" json:"req2xx,omitempty"`
	Req3Xx               int64    `protobuf:"varint,6,opt,name=req3xx" json:"req3xx,omitempty"`
	Req4Xx               int64    `protobuf:"varint,7,opt,name=req4xx" json:"req4xx,omitempty"`
	Req5Xx               int64    `protobuf:"varint,8,opt,name=req5xx" json:"req5xx,omitempty"`
	Others               int64    `protobuf:"varint,9,opt,name=others" json:"others,omitempty"`
	Latency              *Latency `protobuf:"bytes,10,opt,name=latency" json:"latency,omitempty"`
	Rps                  *Rps     `protobuf:"bytes,11,opt,name=rps" json:"rps,omitempty"`
	Error                *Error   `protobuf:"bytes,12,opt,name=error" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_slave_48a80dd1f8c230e6, []int{3}
}
func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (dst *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(dst, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetBytesRead() int64 {
	if m != nil {
		return m.BytesRead
	}
	return 0
}

func (m *Result) GetBytesWritten() int64 {
	if m != nil {
		return m.BytesWritten
	}
	return 0
}

func (m *Result) GetTimeTakenSeconds() float32 {
	if m != nil {
		return m.TimeTakenSeconds
	}
	return 0
}

func (m *Result) GetReq1Xx() int64 {
	if m != nil {
		return m.Req1Xx
	}
	return 0
}

func (m *Result) GetReq2Xx() int64 {
	if m != nil {
		return m.Req2Xx
	}
	return 0
}

func (m *Result) GetReq3Xx() int64 {
	if m != nil {
		return m.Req3Xx
	}
	return 0
}

func (m *Result) GetReq4Xx() int64 {
	if m != nil {
		return m.Req4Xx
	}
	return 0
}

func (m *Result) GetReq5Xx() int64 {
	if m != nil {
		return m.Req5Xx
	}
	return 0
}

func (m *Result) GetOthers() int64 {
	if m != nil {
		return m.Others
	}
	return 0
}

func (m *Result) GetLatency() *Latency {
	if m != nil {
		return m.Latency
	}
	return nil
}

func (m *Result) GetRps() *Rps {
	if m != nil {
		return m.Rps
	}
	return nil
}

func (m *Result) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Error struct {
	Description          string   `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_slave_48a80dd1f8c230e6, []int{4}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Error) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Latency struct {
	Mean                 float32            `protobuf:"fixed32,1,opt,name=mean" json:"mean,omitempty"`
	Stddev               float32            `protobuf:"fixed32,2,opt,name=stddev" json:"stddev,omitempty"`
	Max                  float32            `protobuf:"fixed32,3,opt,name=max" json:"max,omitempty"`
	Percentiles          map[string]float32 `protobuf:"bytes,4,rep,name=percentiles" json:"percentiles,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Latency) Reset()         { *m = Latency{} }
func (m *Latency) String() string { return proto.CompactTextString(m) }
func (*Latency) ProtoMessage()    {}
func (*Latency) Descriptor() ([]byte, []int) {
	return fileDescriptor_slave_48a80dd1f8c230e6, []int{5}
}
func (m *Latency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Latency.Unmarshal(m, b)
}
func (m *Latency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Latency.Marshal(b, m, deterministic)
}
func (dst *Latency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Latency.Merge(dst, src)
}
func (m *Latency) XXX_Size() int {
	return xxx_messageInfo_Latency.Size(m)
}
func (m *Latency) XXX_DiscardUnknown() {
	xxx_messageInfo_Latency.DiscardUnknown(m)
}

var xxx_messageInfo_Latency proto.InternalMessageInfo

func (m *Latency) GetMean() float32 {
	if m != nil {
		return m.Mean
	}
	return 0
}

func (m *Latency) GetStddev() float32 {
	if m != nil {
		return m.Stddev
	}
	return 0
}

func (m *Latency) GetMax() float32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *Latency) GetPercentiles() map[string]float32 {
	if m != nil {
		return m.Percentiles
	}
	return nil
}

type Rps struct {
	Mean                 float32            `protobuf:"fixed32,1,opt,name=mean" json:"mean,omitempty"`
	Stddev               float32            `protobuf:"fixed32,2,opt,name=stddev" json:"stddev,omitempty"`
	Max                  float32            `protobuf:"fixed32,3,opt,name=max" json:"max,omitempty"`
	Percentiles          map[string]float32 `protobuf:"bytes,4,rep,name=percentiles" json:"percentiles,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Rps) Reset()         { *m = Rps{} }
func (m *Rps) String() string { return proto.CompactTextString(m) }
func (*Rps) ProtoMessage()    {}
func (*Rps) Descriptor() ([]byte, []int) {
	return fileDescriptor_slave_48a80dd1f8c230e6, []int{6}
}
func (m *Rps) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rps.Unmarshal(m, b)
}
func (m *Rps) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rps.Marshal(b, m, deterministic)
}
func (dst *Rps) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rps.Merge(dst, src)
}
func (m *Rps) XXX_Size() int {
	return xxx_messageInfo_Rps.Size(m)
}
func (m *Rps) XXX_DiscardUnknown() {
	xxx_messageInfo_Rps.DiscardUnknown(m)
}

var xxx_messageInfo_Rps proto.InternalMessageInfo

func (m *Rps) GetMean() float32 {
	if m != nil {
		return m.Mean
	}
	return 0
}

func (m *Rps) GetStddev() float32 {
	if m != nil {
		return m.Stddev
	}
	return 0
}

func (m *Rps) GetMax() float32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *Rps) GetPercentiles() map[string]float32 {
	if m != nil {
		return m.Percentiles
	}
	return nil
}

type Status struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_slave_48a80dd1f8c230e6, []int{7}
}
func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (dst *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(dst, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

type JobResultResponse struct {
	Code                 int64              `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Result               map[string]float32 `protobuf:"bytes,2,rep,name=result" json:"result,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *JobResultResponse) Reset()         { *m = JobResultResponse{} }
func (m *JobResultResponse) String() string { return proto.CompactTextString(m) }
func (*JobResultResponse) ProtoMessage()    {}
func (*JobResultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_slave_48a80dd1f8c230e6, []int{8}
}
func (m *JobResultResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobResultResponse.Unmarshal(m, b)
}
func (m *JobResultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobResultResponse.Marshal(b, m, deterministic)
}
func (dst *JobResultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobResultResponse.Merge(dst, src)
}
func (m *JobResultResponse) XXX_Size() int {
	return xxx_messageInfo_JobResultResponse.Size(m)
}
func (m *JobResultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JobResultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JobResultResponse proto.InternalMessageInfo

func (m *JobResultResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *JobResultResponse) GetResult() map[string]float32 {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*Job)(nil), "models.Job")
	proto.RegisterMapType((map[string]string)(nil), "models.Job.HeadersEntry")
	proto.RegisterType((*Stats)(nil), "models.Stats")
	proto.RegisterType((*Spec)(nil), "models.Spec")
	proto.RegisterType((*Result)(nil), "models.Result")
	proto.RegisterType((*Error)(nil), "models.Error")
	proto.RegisterType((*Latency)(nil), "models.Latency")
	proto.RegisterMapType((map[string]float32)(nil), "models.Latency.PercentilesEntry")
	proto.RegisterType((*Rps)(nil), "models.Rps")
	proto.RegisterMapType((map[string]float32)(nil), "models.Rps.PercentilesEntry")
	proto.RegisterType((*Status)(nil), "models.Status")
	proto.RegisterType((*JobResultResponse)(nil), "models.JobResultResponse")
	proto.RegisterMapType((map[string]float32)(nil), "models.JobResultResponse.ResultEntry")
}

func init() {
	proto.RegisterFile("github.com/yiqinguo/armyant/pkg/models/slave.proto", fileDescriptor_slave_48a80dd1f8c230e6)
}

var fileDescriptor_slave_48a80dd1f8c230e6 = []byte{
	// 822 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xcd, 0x6e, 0xe4, 0x44,
	0x10, 0xd6, 0xd8, 0x33, 0x4e, 0xa6, 0x1c, 0x42, 0x68, 0xd0, 0xca, 0x8a, 0x02, 0x1a, 0x0d, 0x62,
	0x15, 0x38, 0xcc, 0x80, 0x77, 0x91, 0x60, 0x25, 0x16, 0x09, 0xb4, 0x12, 0x89, 0x90, 0x40, 0x9d,
	0x95, 0x38, 0xfb, 0xa7, 0xc8, 0x98, 0x8c, 0xbb, 0x9d, 0xee, 0x76, 0x64, 0xbf, 0x08, 0x77, 0x0e,
	0x3c, 0x09, 0x47, 0x1e, 0x84, 0x27, 0xe0, 0x8e, 0xba, 0xba, 0x3d, 0x71, 0x7e, 0x24, 0x84, 0xd0,
	0xde, 0xea, 0xfb, 0xaa, 0xca, 0x5d, 0xff, 0x86, 0xf4, 0xb2, 0x32, 0x9b, 0x36, 0x5f, 0x15, 0xb2,
	0x5e, 0xf7, 0xd5, 0x75, 0x25, 0x2e, 0x5b, 0xb9, 0xce, 0x54, 0xdd, 0x67, 0xc2, 0xac, 0x9b, 0xab,
	0xcb, 0x75, 0x2d, 0x4b, 0xdc, 0xea, 0xb5, 0xde, 0x66, 0x37, 0xb8, 0x6a, 0x94, 0x34, 0x92, 0x45,
	0x8e, 0x5b, 0xfe, 0x15, 0x40, 0x78, 0x2e, 0x73, 0x76, 0x08, 0x41, 0x55, 0x26, 0x93, 0xc5, 0xe4,
	0x74, 0xce, 0x83, 0xaa, 0x64, 0x0b, 0x88, 0x0b, 0x29, 0x04, 0x16, 0xa6, 0x92, 0x42, 0x27, 0xc1,
	0x62, 0x72, 0x1a, 0xf2, 0x31, 0xc5, 0x9e, 0x40, 0x54, 0xa3, 0xd9, 0xc8, 0x32, 0x09, 0xc9, 0xcb,
	0x23, 0xc6, 0x60, 0x9a, 0xcb, 0xb2, 0x4f, 0xa6, 0xc4, 0x92, 0xcc, 0x52, 0xd8, 0xdb, 0x60, 0x56,
	0xa2, 0xd2, 0xc9, 0x6c, 0x11, 0x9e, 0xc6, 0x69, 0xb2, 0x72, 0xef, 0xaf, 0xce, 0x65, 0xbe, 0xfa,
	0xce, 0xa9, 0x5e, 0x09, 0xa3, 0x7a, 0x3e, 0x18, 0xb2, 0x63, 0xd8, 0x57, 0x78, 0xdd, 0xa2, 0x36,
	0x3a, 0x89, 0xe8, 0xf9, 0x1d, 0x66, 0x47, 0x10, 0xb6, 0x6a, 0x9b, 0xec, 0xd1, 0x13, 0x56, 0xb4,
	0xd6, 0x65, 0xab, 0x32, 0x1b, 0x5a, 0xb2, 0x4f, 0xf4, 0x0e, 0xb3, 0x13, 0x98, 0x6f, 0x2a, 0x6d,
	0xa4, 0xea, 0xcf, 0xca, 0x64, 0x4e, 0xca, 0x5b, 0xc2, 0xc6, 0x2b, 0xb2, 0x1a, 0x13, 0x70, 0xf1,
	0x5a, 0x99, 0x72, 0xcb, 0xb4, 0x41, 0x95, 0xc4, 0x3e, 0x37, 0x42, 0xc7, 0x2f, 0xe0, 0x60, 0x1c,
	0xac, 0x8d, 0xe3, 0x0a, 0x7b, 0x5f, 0x36, 0x2b, 0xb2, 0xf7, 0x60, 0x76, 0x93, 0x6d, 0x5b, 0xa4,
	0x8a, 0xcd, 0xb9, 0x03, 0x2f, 0x82, 0x2f, 0x26, 0xcb, 0xdf, 0x27, 0x30, 0xbb, 0x30, 0x99, 0xd1,
	0x6c, 0x01, 0x53, 0xdd, 0x60, 0x41, 0x6e, 0x71, 0x7a, 0x30, 0x94, 0xe2, 0xa2, 0xc1, 0x82, 0x93,
	0x86, 0x3d, 0x85, 0x48, 0xa1, 0x6e, 0xb7, 0x86, 0x3e, 0x13, 0xa7, 0x87, 0x83, 0x0d, 0x27, 0x96,
	0x7b, 0xad, 0x7d, 0xed, 0x17, 0x99, 0x9f, 0x0d, 0x2d, 0x70, 0xe0, 0x6e, 0xbe, 0xd3, 0xfb, 0xf9,
	0x7e, 0x00, 0x50, 0x09, 0x6d, 0x32, 0x51, 0x94, 0x67, 0x65, 0x32, 0x23, 0xf5, 0x88, 0x59, 0xfe,
	0x1a, 0xc0, 0xd4, 0x86, 0xc2, 0x3e, 0x85, 0x77, 0x45, 0x5b, 0xe7, 0xa8, 0x7e, 0xf8, 0xf9, 0xdb,
	0xd1, 0x28, 0x4c, 0xa8, 0x17, 0x8f, 0xa9, 0x6c, 0x13, 0x0c, 0x6a, 0xf3, 0xba, 0x6f, 0x86, 0xfc,
	0x77, 0x98, 0x7d, 0x02, 0x47, 0x83, 0x0b, 0x1f, 0xda, 0x1a, 0xd2, 0xa7, 0x1e, 0xf0, 0xa3, 0xd1,
	0x9a, 0xde, 0x19, 0x2d, 0xdf, 0xf6, 0xd9, 0x6d, 0xdb, 0x87, 0x61, 0x8b, 0x46, 0xc3, 0xf6, 0x04,
	0x22, 0x6d, 0x14, 0x66, 0x35, 0xcd, 0xc7, 0x3e, 0xf7, 0x88, 0x3d, 0x85, 0x43, 0x53, 0xd5, 0x28,
	0x5b, 0x73, 0x81, 0x85, 0x14, 0xa5, 0xa6, 0x41, 0x09, 0xf9, 0x3d, 0xd6, 0xfa, 0x17, 0xdb, 0x0a,
	0x85, 0xf1, 0xb3, 0xe2, 0xd1, 0xf2, 0xef, 0x00, 0x22, 0x57, 0x7f, 0x5b, 0xe1, 0xbc, 0x37, 0xa8,
	0x39, 0x66, 0xa5, 0x2f, 0xc8, 0x2d, 0xc1, 0x96, 0x70, 0x40, 0xe0, 0x27, 0x55, 0x19, 0x83, 0xc2,
	0x2f, 0xcf, 0x1d, 0xce, 0x96, 0xc3, 0x3e, 0xfb, 0x3a, 0xbb, 0x42, 0x31, 0x84, 0x63, 0xcb, 0x11,
	0xf0, 0x07, 0xbc, 0x0d, 0x48, 0xe1, 0xf5, 0x67, 0x5d, 0x47, 0xe5, 0x08, 0xb9, 0x47, 0x9e, 0x4f,
	0xbb, 0x8e, 0x2a, 0xe2, 0xf8, 0x74, 0xc7, 0x3f, 0xeb, 0x3a, 0xbf, 0x37, 0x1e, 0x79, 0xfe, 0x79,
	0xd7, 0x51, 0x61, 0x1c, 0xff, 0x7c, 0xc7, 0x7f, 0xde, 0x75, 0xbe, 0x20, 0x1e, 0x59, 0x5e, 0x9a,
	0x8d, 0x5d, 0xda, 0xb9, 0xe3, 0x1d, 0x62, 0x1f, 0xc3, 0xde, 0x36, 0x33, 0x28, 0x8a, 0x9e, 0x96,
	0x26, 0x4e, 0xdf, 0x1e, 0xc6, 0xf3, 0x7b, 0x47, 0xf3, 0x41, 0xcf, 0xde, 0x87, 0x50, 0x35, 0x9a,
	0xb6, 0x28, 0x4e, 0xe3, 0xdd, 0x14, 0x37, 0x9a, 0x5b, 0x9e, 0x7d, 0x08, 0x33, 0x54, 0x4a, 0xaa,
	0xe4, 0x80, 0x0c, 0xde, 0x1a, 0x0c, 0x5e, 0x59, 0x92, 0x3b, 0xdd, 0xf2, 0x6b, 0x98, 0x11, 0xb6,
	0x37, 0xa9, 0x44, 0x5d, 0xa8, 0xaa, 0xa1, 0x35, 0x77, 0x5b, 0x37, 0xa6, 0xec, 0x3e, 0x14, 0xb2,
	0x15, 0xc6, 0x97, 0xdc, 0x81, 0xe5, 0x9f, 0x13, 0xd8, 0xf3, 0x91, 0xd9, 0x81, 0xa9, 0x31, 0x73,
	0xce, 0x01, 0x27, 0xd9, 0x0d, 0x4c, 0x59, 0xe2, 0x0d, 0xb9, 0x05, 0xdc, 0x23, 0x3b, 0x6e, 0x75,
	0xd6, 0xf9, 0xb6, 0x58, 0x91, 0x7d, 0x03, 0x71, 0x83, 0xaa, 0x40, 0x61, 0xaa, 0x2d, 0xea, 0x64,
	0x4a, 0xb7, 0x6c, 0x71, 0x2f, 0xfb, 0xd5, 0x8f, 0xb7, 0x26, 0xee, 0xa6, 0x8d, 0x9d, 0x8e, 0x5f,
	0xc2, 0xd1, 0x7d, 0x83, 0x7f, 0xbb, 0x23, 0xc1, 0xf8, 0x8e, 0xfc, 0x31, 0x81, 0x90, 0x37, 0xfa,
	0x7f, 0x66, 0xf2, 0xf2, 0xb1, 0x4c, 0x4e, 0x46, 0x0d, 0x7a, 0xc3, 0x59, 0x9c, 0x40, 0x64, 0x8f,
	0x61, 0x4b, 0x79, 0x14, 0xb2, 0x44, 0xbf, 0x46, 0x24, 0x2f, 0x7f, 0x9b, 0xc0, 0x3b, 0xe7, 0x32,
	0xf7, 0xd7, 0x0e, 0x75, 0x23, 0x85, 0xc6, 0xc7, 0x2c, 0xd9, 0x57, 0xa3, 0x4b, 0x69, 0x53, 0xf8,
	0x68, 0xf4, 0x63, 0xb9, 0xeb, 0xee, 0x6f, 0xa7, 0xcb, 0xc5, 0x3b, 0x1d, 0x7f, 0x09, 0xf1, 0x88,
	0xfe, 0x2f, 0x19, 0xe4, 0x11, 0xfd, 0x48, 0x9f, 0xfd, 0x13, 0x00, 0x00, 0xff, 0xff, 0xea, 0xf8,
	0xcd, 0x9f, 0x7e, 0x07, 0x00, 0x00,
}
